
function [meta_dbn, nodes_map]=make_meta_bnet(Gm, Im, Go, Io, time)

    % make ODE and BD models
    [ode_dbn_factory]= ...
        make_ode_dbn_factory(Gm, Im, time);
    [spt_dbn_factory]= ...
        make_spt_dbn_factory(Go, Io, time);
    meta_dbn_factory= ...
        merge_dbn_factories(ode_dbn_factory, ...
                              spt_dbn_factory);
    weights_Iref_map_T0= containers.Map(); % parents in slice t
    weights_Iref_map_T1= containers.Map(); % parents in slice t
    weights_Iref_map_T0('ODE.Ipm')= 0.5;
    weights_Iref_map_T0('SPT.Ipm')= 0.5;
    CPDFactory_Iref = ...
        CPDFactory('Gaussian_CPD', 'R.Ipm', 0, ...
        {'mean', 0.0, 'cov', 5.0}, ...
        weights_Iref_map_T0, ...
        weights_Iref_map_T1);
    add_CPD_factories(meta_dbn_factory, {CPDFactory_Iref}, false);

    [meta_dbn, ~, ~, nodes_map] = create_dbn(meta_dbn_factory);
    
end
