% Make a DBN for the meta-model with the following variables
%
% Time-dependent variables
%
% Coupling variables
% Gex.C, Gcell.C, Scell.C
%
% Observed variables
%
% Time-invariant variables
%
% Parameters
%
% To generate a conditional gaussian model

function [meta_dbn, nodes_map]=make_meta_dbn3(DGd_mean_postprandial, DGd_cov_postprandial, Gb_mean_postprandial,...
                                              Gb_cov_postprandial, G_mean_postprandial, G_cov_postprandial,...
                                              DG_mean_postprandial, DG_cov_postprandial, Y_mean_postprandial,...
                                              Y_cov_postprandial, S_mean_postprandial, S_cov_postprandial,...
                                              I_mean_postprandial, I_cov_postprandial, Sb_mean_postprandial,...
                                              Sb_cov_postprandial, alpha_postprandial, beta_postprandial,...
                                              gamma_postprandial, k1_postprandial,k2_postprandial,...
                                              k3_postprandial, k4_postprandial, K_postprandial,...
                                              dt_postprandial, cov_scale_postprandial,...
                                              Scell_mean_pancreas, Scell_cov_pancreas, Sislet_mean_pancreas, ...
                                              Sislet_cov_pancreas, Spancreas_mean_pancreas, Spancreas_cov_pancreas, ...
                                              cov_scale_pancreas, Nc_pancreas, Ni_pancreas,...
                                              G_mean_exocytosis, kt_mean_exocytosis, Npatch_mean_exocytosis,...
                                              Nvesicle_mean_exocytosis, Ninsulin_mean_exocytosis, Rcell_mean_exocytosis,...
                                              Dvesicle_mean_exocytosis, S_mean_exocytosis, G_cov_exocytosis,...
                                              kt_cov_exocytosis, Npatch_cov_exocytosis, Nvesicle_cov_exocytosis, ...
                                              Ninsulin_cov_exocytosis, Rcell_cov_exocytosis,Dvesicle_cov_exocytosis, ...
                                              S_cov_exocytosis,...
                                              cov_scale_exocytosis,...
                                              kG_exocytosis, alpha_exocytosis, ...
                                              kp_exocytosis,beta_exocytosis, kinsulin_exocytosis, ...
                                              kD_exocytosis, kR_exocytosis, ...
                                              S_ve_weight, G_pr_weight, G_c_weight, S_pa_weight, ...
                                              S_cell_obs_weight, G_obs_weight, G_cell_obs_weight, S_pa_obs_weight, ...
                                              S_cell_obs_mean, S_cell_obs_cov, S_pa_obs_mean, S_pa_obs_cov, ...
                                              G_pl_obs_mean, G_pl_obs_cov, G_cell_obs_mean, G_cell_obs_cov);


    % make DBNs for all input models
    [pancreas_dbn_factory]= make_pancreas_dbn(Scell_mean_pancreas, Scell_cov_pancreas, Sislet_mean_pancreas, ...
                                              Sislet_cov_pancreas, Spancreas_mean_pancreas, Spancreas_cov_pancreas, ...
                                              cov_scale_pancreas, Nc_pancreas, Ni_pancreas, S_pa_weight, S_pa_obs_weight, ...
                                              S_pa_obs_mean, S_pa_obs_cov);
                                          
    [exocytosis_dbn_factory]= make_exocytosis_dbn(G_mean_exocytosis, kt_mean_exocytosis, Npatch_mean_exocytosis,...
                                                  Nvesicle_mean_exocytosis, Ninsulin_mean_exocytosis, Rcell_mean_exocytosis,...
                                                  Dvesicle_mean_exocytosis, S_mean_exocytosis, G_cov_exocytosis,...
                                                  kt_cov_exocytosis, Npatch_cov_exocytosis, Nvesicle_cov_exocytosis, ...
                                                  Ninsulin_cov_exocytosis, Rcell_cov_exocytosis,Dvesicle_cov_exocytosis, ...
                                                  S_cov_exocytosis,...
                                                  cov_scale_exocytosis,...
                                                  kG_exocytosis, alpha_exocytosis, ...
                                                  kp_exocytosis,beta_exocytosis, kinsulin_exocytosis, ...
                                                  kD_exocytosis, kR_exocytosis, S_ve_weight, S_cell_obs_weight, ...
                                                  S_cell_obs_mean, S_cell_obs_cov);                                     
                                          
    [postprandial_dbn_factory]= make_postprandial_dbn(DGd_mean_postprandial, DGd_cov_postprandial, Gb_mean_postprandial,...
                                              Gb_cov_postprandial, G_mean_postprandial, G_cov_postprandial,...
                                              DG_mean_postprandial, DG_cov_postprandial, Y_mean_postprandial,...
                                              Y_cov_postprandial, S_mean_postprandial, S_cov_postprandial,...
                                              I_mean_postprandial, I_cov_postprandial, Sb_mean_postprandial,...
                                              Sb_cov_postprandial, alpha_postprandial, beta_postprandial,...
                                              gamma_postprandial, k1_postprandial,k2_postprandial,...
                                              k3_postprandial, k4_postprandial, K_postprandial,...
                                              dt_postprandial, cov_scale_postprandial,...
                                              G_c_weight, G_pr_weight, G_obs_weight, G_cell_obs_weight,...
                                              G_pl_obs_mean, G_pl_obs_cov, G_cell_obs_mean, G_cell_obs_cov);
    
    
                                              
    % make DBNs to generate meta- DBN
    meta_dbn_factory= ...
        merge_dbn_factories(postprandial_dbn_factory, pancreas_dbn_factory, exocytosis_dbn_factory);
                     
           
    % re-define CPDs of connected variables
    weights_Scell0_map_T0= containers.Map(); % parents in slice t
    weights_Scell0_map_T1= containers.Map(); % parents in slice t+1
    weights_Scell0_map_T0('S.exocytosis')= S_ve_weight;
    weights_Scell0_map_T0('Scell.obs')= S_cell_obs_weight;
    CPDFactory_Scell_obs = ...
        CPDFactory('Gaussian_CPD', 'Scell.C', 0, {'mean', 0.0, 'cov', S_cell_obs_cov}, ...
        weights_Scell0_map_T0, weights_Scell0_map_T1); % Scell.C = 1*S.exocytosis + 1*S.cell_obs, 1e-22
    
    
    weights_G0_map_T0= containers.Map(); 
    weights_G0_map_T1= containers.Map();
    weights_G0_map_T0('G.postprandial')= G_pr_weight;
    weights_G0_map_T0('G.obs')= G_obs_weight;
    CPDFactory_G_obs =  ...
       CPDFactory('Gaussian_CPD', 'G.C', 0, {'mean', 0.0,'cov', G_pl_obs_cov}, ...
       weights_G0_map_T0, weights_G0_map_T1 ); % Gcell.obs = 1.0 * Gcell.C 1e-4
    
    weights_Gcell0_map_T0= containers.Map(); 
    weights_Gcell0_map_T1= containers.Map();
    weights_Gcell0_map_T0('G.C')= G_c_weight;
    weights_Gcell0_map_T0('Gcell.obs')= G_cell_obs_weight;
    CPDFactory_Gcell_obs = ...
        CPDFactory('Gaussian_CPD', 'Gcell.C', 0, {'mean', 0.0, 'cov', G_cell_obs_cov}, ...
        weights_Gcell0_map_T0, weights_Gcell0_map_T1); % Gcell.C = 0.5 * G.C 1e-4
    
    
    weights_Spa0_map_T0= containers.Map(); % parents in slice t
    weights_Spa0_map_T1= containers.Map(); % parents in slice t+1
    weights_Spa0_map_T0('Spa.pancreas')= S_pa_weight;
    weights_Spa0_map_T0('Spa.obs')= S_pa_obs_weight;
    CPDFactory_Spa_obs = ...
        CPDFactory('Gaussian_CPD', 'Spa.C', 0, {'mean', 0.0, 'cov', S_pa_obs_cov}, ...
        weights_Spa0_map_T0, weights_Spa0_map_T1); % 1e-5
    
    
    weights_S0_map_T0= containers.Map();
    weights_S0_map_T1= containers.Map(); 
    weights_S0_map_T0('DGd.postprandial')= 0.0;
    weights_S0_map_T0('Sb.postprandial')= 0;
    weights_S0_map_T0('Spa.C')= 1/2;
    weights_S0_map_T0('Y.postprandial')= 0.0;
    CPDFactory_S0 =  ...
        CPDFactory('Gaussian_CPD', 'S.postprandial', 0, {'mean', Sb_mean_postprandial/2, 'cov', Sb_cov_postprandial*cov_scale_postprandial}, ...
        weights_S0_map_T0, weights_S0_map_T1); % S.postprandial = 1/2 * Scell.C
    
    weights_S1_map_T0= containers.Map(); 
    weights_S1_map_T1= containers.Map();
    weights_S1_map_T1('DGd.postprandial')= K_postprandial/2;
    weights_S1_map_T1('Sb.postprandial')= 1/2;
    weights_S1_map_T1('Spa.C')= 1/2;
    weights_S1_map_T1('Y.postprandial')= 1/2;
    weights_S1_map_T0('S.postprandial')= 0.0;
    CPDFactory_S1=  ...
        CPDFactory('Gaussian_CPD', 'S.postprandial', 1, ...
        {'mean', 0.0, 'cov', Sb_cov_postprandial*cov_scale_postprandial}, ...
        weights_S1_map_T0, weights_S1_map_T1); % S(t+1) = 0.0 * S(t) + K_mean_postprandial/3 * DGex(t+1) + 2/3 * Scell.C(t+1) + 1/3 * Y(t+1)

	%add_CPD_factories(meta_dbn_factory, {CPDFactory_Scell0, CPDFactory_Gin0, CPDFactory_S0, CPDFactory_S1, ...
    %    CPDFactory_Scellobs}, false);
    add_CPD_factories(meta_dbn_factory, {CPDFactory_Scell_obs, CPDFactory_Gcell_obs, CPDFactory_S0, ...
        CPDFactory_S1, CPDFactory_G_obs, CPDFactory_Spa_obs}, false);
    [meta_dbn, ~, ~, nodes_map] = create_dbn(meta_dbn_factory);
    
end
