% Make a DBN for the exocytosis model with the following variables
%
% Time-dependent variables
%
% Reference variables
% Gex.ref, Gin.ref, Scell.ref
%
% Observed variables
%
% Time-invariant variables
%
% Parameters
%
% To generate a conditional gaussian model
%
% All variables display gaussian distributions.

% To generate a conditional gaussian model
function [dbn_factory]= make_exocytosis_dbn(Gin_mean_exocytosis, k_mean_exocytosis, Npatch_mean_exocytosis,...
                                            Nisg_mean_exocytosis, Ninsulin_mean_exocytosis, Rpbc_mean_exocytosis,...
                                            Disg_mean_exocytosis, S_mean_exocytosis, Gin_cov_exocytosis,...
                                            k_cov_exocytosis, Npatch_cov_exocytosis, Nisg_cov_exocytosis, ...
                                            Ninsulin_cov_exocytosis, Rpbc_cov_exocytosis,Disg_cov_exocytosis, ...
                                            S_cov_exocytosis,...
                                            min_cov_exocytosis,...
                                            S_w_S_exocytosis, Gin_w_S_exocytosis, S_w_k_exocytosis, ...
                                            Npatch_w_S_exocytosis,S_w_Nisg_exocytosis, Ninsulin_w_S_exocytosis, ...
                                            Disg_w_S_exocytosis, Rpbc_w_S_exocytosis);

    node_names=  {'Gin.ref','Gin.exocytosis', 'k.exocytosis', 'Npatch.exocytosis','Nisg.exocytosis',...
                  'Disg.exocytosis', 'Ninsulin.exocytosis','Rpbc.exocytosis', 'S.exocytosis', 'Scell.ref'};
    
    % Intra - in one time slice
    edges_intra= { 'Gin.ref','Gin.exocytosis';'S.exocytosis','k.exocytosis';'Npatch.exocytosis', 'S.exocytosis';...
                   'S.exocytosis','Nisg.exocytosis'; 'Disg.exocytosis', 'S.exocytosis'; 'Ninsulin.exocytosis','S.exocytosis';...
                   'Rpbc.exocytosis','S.exocytosis';'S.exocytosis','Scell.ref'};
    
    % Inter - between time slices
    edges_inter= { 'Gin.exocytosis', 'Gin.exocytosis'; 'Gin.exocytosis', 'S.exocytosis'; 'S.exocytosis', 'S.exocytosis';...
                   'k.exocytosis', 'k.exocytosis';'Nisg.exocytosis', 'Nisg.exocytosis'; 'Npatch.exocytosis', 'Npatch.exocytosis';...
                   'Ninsulin.exocytosis', 'Ninsulin.exocytosis'};
    
    % 'Equivalence classes' specify how the template is initiated and rolled
    % Specify which CPD is associates with each node in either time
    % slice 1 (eclass1) or in slice 2 onwards (eclass2)
    eclass1_map= containers.Map();
    eclass2_map= containers.Map();
    for i=1:numel(node_names)
        node_name= node_names{i};
        cpd_name= [ node_name '.intra' ];
        eclass1_map(node_name) = cpd_name;
        eclass2_map(node_name) = cpd_name; % default - to be changed for some special cases
    end
    eclass2_map('Gin.exocytosis')= 'Gin.exocytosis.inter';
    eclass2_map('S.exocytosis')= 'S.exocytosis.inter';
    eclass2_map('k.exocytosis')= 'k.exocytosis.inter'; 
    eclass2_map('Nisg.exocytosis')= 'Nisg.exocytosis.inter';   
    eclass2_map('Npatch.exocytosis')= 'Npatch.exocytosis.inter';   
    eclass2_map('Ninsulin.exocytosis')= 'Ninsulin.exocytosis.inter';   
    
    % elcass1 (time-slice 0 or all parents are in the same time slice)
    % When using clamp, the root node is clamped to the N(0,I) distribution, so that we will not update these parameters during learninGex. 
    CPDFactories= {};
    CPDFactories{end+1} = ...         
        CPDFactory('Gaussian_CPD', 'Gin.ref', 0, ...
        {'mean', Gin_mean_exocytosis, 'cov', Gin_cov_exocytosis}); % Gin.ref
    
    CPDFactories{end+1} = ...         
        CPDFactory('Gaussian_CPD', 'Gin.exocytosis', 0, ...
        {'mean', 0.0, 'cov', Gin_cov_exocytosis*min_cov_exocytosis, 'weights', 1.0}); % Gin = Gin.ref
    
    CPDFactories{end+1} = ...
        CPDFactory('Gaussian_CPD', 'k.exocytosis', 0, ...
        {'mean', k_mean_exocytosis/2, 'cov', k_cov_exocytosis, 'weights', S_w_k_exocytosis/2}); % k
    
    CPDFactories{end+1} = ...
        CPDFactory('Gaussian_CPD', 'Npatch.exocytosis', 0, ...
        {'mean', Npatch_mean_exocytosis, 'cov', Npatch_cov_exocytosis}); % Npatch
    
    CPDFactories{end+1} = ...         
        CPDFactory('Gaussian_CPD', 'Nisg.exocytosis', 0, ...
        {'mean', 0.0, 'cov', Nisg_cov_exocytosis*min_cov_exocytosis, 'weights', S_w_Nisg_exocytosis}); % Nisg
    
    CPDFactories{end+1} = ...         
        CPDFactory('Gaussian_CPD', 'Ninsulin.exocytosis', 0, ...
        {'mean', Ninsulin_mean_exocytosis, 'cov', Ninsulin_cov_exocytosis}); % Ninsulin
    
    CPDFactories{end+1} = ...         
        CPDFactory('Gaussian_CPD', 'Rpbc.exocytosis', 0, ...
        {'mean', Rpbc_mean_exocytosis, 'cov', Rpbc_cov_exocytosis}); % Rpbc
    
    CPDFactories{end+1} = ...         
        CPDFactory('Gaussian_CPD', 'Disg.exocytosis', 0, ...
        {'mean', Disg_mean_exocytosis, 'cov', Disg_cov_exocytosis}); % Disg
    
    weights_S0_map_T0= containers.Map(); % parents in slice t
    weights_S0_map_T1= containers.Map(); % parents in slice t+1
    weights_S0_map_T0('Npatch.exocytosis')= 0.0;
    weights_S0_map_T0('Ninsulin.exocytosis')= 0.0;
    weights_S0_map_T0('Disg.exocytosis')= 0.0;
    weights_S0_map_T0('Nisg.exocytosis')= 0.0;
    weights_S0_map_T0('Rpbc.exocytosis')= 0.0;
    CPDFactories{end+1} = ...         
        CPDFactory('Gaussian_CPD', 'S.exocytosis', 0, ...
        {'mean', S_mean_exocytosis, 'cov', S_cov_exocytosis}, ...
        weights_S0_map_T0, weights_S0_map_T1); % S
    
    CPDFactories{end+1} = ...
        CPDFactory('Gaussian_CPD', 'Scell.ref', 0, ...
        { 'mean', 0.0,'cov', S_cov_exocytosis*min_cov_exocytosis, 'weights', 1.0} ); % Scell.ref = S
  
    % eclass2 (time-slice t+1 with parents in the previous time slice)
    weights_k1_map_T0= containers.Map(); 
    weights_k1_map_T1= containers.Map(); 
    weights_k1_map_T0('k.exocytosis')= 0.5; 
    weights_k1_map_T1('S.exocytosis')= S_w_k_exocytosis/2;
    CPDFactories{end+1} = ...
       CPDFactory('Gaussian_CPD', 'k.exocytosis', 1, ...
        {'mean', 0.0, 'cov', k_cov_exocytosis*min_cov_exocytosis}, ...
        weights_k1_map_T0, weights_k1_map_T1); % k(t+1) = 1.0 * k(t) 
    
    CPDFactories{end+1} = ...
       CPDFactory('Gaussian_CPD', 'Npatch.exocytosis', 1, ...
        {'mean', 0.0, 'cov', Npatch_cov_exocytosis*min_cov_exocytosis,  'weights', 1.0} ); % Npatch(t+1) = 1.0 * Npatch(t) 
    
    weights_Nisg1_map_T0= containers.Map(); 
    weights_Nisg1_map_T1= containers.Map(); 
    weights_Nisg1_map_T0('Nisg.exocytosis')= 0.0; 
    weights_Nisg1_map_T1('S.exocytosis')= S_w_Nisg_exocytosis;
    CPDFactories{end+1} = ...
       CPDFactory('Gaussian_CPD', 'Nisg.exocytosis', 1, ...
        {'mean', 0.0, 'cov', Nisg_cov_exocytosis*min_cov_exocytosis}, ...
        weights_Nisg1_map_T0, weights_Nisg1_map_T1); % k(t+1) = 1.0 * k(t)     CPDFactories{end+1} = ...
   
    CPDFactories{end+1} = ...
       CPDFactory('Gaussian_CPD', 'Ninsulin.exocytosis', 1, ...
        {'mean', 0.0, 'cov', Ninsulin_cov_exocytosis*min_cov_exocytosis,  'weights', 1.0} ); % Npatch(t+1) = 1.0 * Npatch(t) 
    
    weights_Gin1_map_T0= containers.Map(); 
    weights_Gin1_map_T1= containers.Map(); 
    weights_Gin1_map_T0('Gin.exocytosis')= 0.0; 
    weights_Gin1_map_T1('Gin.ref')= 1.0;
    CPDFactories{end+1} = ...         
        CPDFactory('Gaussian_CPD', 'Gin.exocytosis', 1, ...
        {'mean', 0.0, 'cov', Gin_cov_exocytosis*min_cov_exocytosis}, ...
        weights_Gin1_map_T0, weights_Gin1_map_T1); % Gin(t+1) = 1.0 * Gin.ref + 0.0 * Gin(t)
    
    weights_S1_map_T0= containers.Map(); 
    weights_S1_map_T1= containers.Map(); 
    weights_S1_map_T0('S.exocytosis')= S_w_S_exocytosis; 
    weights_S1_map_T0('Gin.exocytosis')= Gin_w_S_exocytosis; 
    weights_S1_map_T1('Npatch.exocytosis')= Npatch_w_S_exocytosis; 
    weights_S1_map_T1('Ninsulin.exocytosis')= Ninsulin_w_S_exocytosis; 
    weights_S1_map_T1('Disg.exocytosis')= Disg_w_S_exocytosis;
    weights_S1_map_T1('Rpbc.exocytosis')= Rpbc_w_S_exocytosis;
    CPDFactories{end+1} = ...         
        CPDFactory('Gaussian_CPD', 'S.exocytosis', 1, ...
        {'mean', 0.0, 'cov', S_cov_exocytosis*min_cov_exocytosis}, ...
        weights_S1_map_T0, weights_S1_map_T1); % S(t+1) = S_w_S_exocytosis*S(t) + Gin_w_S_exocytosis*Gin(t) + k_w_S_exocytosis * k(t+1) 
                                               % Npatch_w_S_exocytosis*Npatch(t+1) + Nisg_w_S_exocytosis * Nisg(t+1) + Ninsulin_w_S_exocytosis * Ninsulin(t+1)
                                               % + Disg_w_S_exocytosis*Disg + Rpbc_w_S_exocytosis*Rpbc 

    % Final DBN factory
    dbn_factory= DBNFactory( ...
        node_names, edges_intra, edges_inter, ...
        eclass1_map, eclass2_map, CPDFactories);
end    

