% Make a DBN for the meta-model with the following variables
%
% Time-dependent variables
%
% Reference variables
% Gex.ref, Gin.ref, Scell.ref
%
% Observed variables
%
% Time-invariant variables
%
% Parameters
%
% To generate a conditional gaussian model

function [meta_dbn, nodes_map]=make_meta_dbn6(Gex_mean_postprandial, Y_mean_postprandial, alpha_mean_postprandial,...
                                              beta_mean_postprandial, gamma_mean_postprandial, k1_mean_postprandial, ...
                                              k2_mean_postprandial, K_mean_postprandial, dt_mean_postprandial_min, ...
                                              Gb_mean_postprandial, DGintake_mean_postprandial, Sb_mean_postprandial, ...
                                              I_mean_postprandial,...
                                              Gex_cov_postprandial, Y_cov_postprandial, Gb_cov_postprandial, ...
                                              DGintake_cov_postprandial, Sb_cov_postprandial, I_cov_postprandial,...
                                              min_cov_postprandial,G_minus_Gb_w_G_postprandial,S_w_I_postprandial,...
                                              Scell_mean_pancreas, Scell_cov_pancreas, Sislet_mean_pancreas, ...
                                              Sislet_cov_pancreas, Spancreas_mean_pancreas, Spancreas_cov_pancreas, ...
                                              min_cov_pancreas, Scell_w_Sislet_pancreas, Sislet_w_Spancreas_pancreas,...
                                              Gin_mean_exocytosis, k_mean_exocytosis, Npatch_mean_exocytosis,...
                                              Nisg_mean_exocytosis, Ninsulin_mean_exocytosis, Rpbc_mean_exocytosis,...
                                              Disg_mean_exocytosis, S_mean_exocytosis, Gin_cov_exocytosis,...
                                              k_cov_exocytosis, Npatch_cov_exocytosis, Nisg_cov_exocytosis, ...
                                              Ninsulin_cov_exocytosis, Rpbc_cov_exocytosis,Disg_cov_exocytosis, ...
                                              S_cov_exocytosis,...
                                              min_cov_exocytosis,...
                                              S_w_S_exocytosis, Gin_w_S_exocytosis, S_w_k_exocytosis, ...
                                              Npatch_w_S_exocytosis,S_w_Nisg_exocytosis, Ninsulin_w_S_exocytosis, ...
                                              Disg_w_S_exocytosis, Rpbc_w_S_exocytosis,...
                                              Gin_mean_signaling, ATP_mean_signaling, GLP1_mean_signaling,...
                                              GLP1R_mean_signaling, cAMP_mean_signaling, Ca_mean_signaling,...
                                              S_mean_signaling, ...
                                              Gin_cov_signaling, ATP_cov_signaling, GLP1_cov_signaling, ...
                                              GLP1R_cov_signaling, cAMP_cov_signaling, Ca_cov_signaling, ...
                                              S_cov_signaling, min_cov_signaling,...
                                              Gin_w_ATP_signaling, ATP_w_ATP_signaling, GLP1_w_GLP1R_signaling,...
                                              ATP_w_cAMP_signaling, GLP1R_w_cAMP_signaling, cAMP_w_cAMP_signaling,...
                                              cAMP_w_Ca_signaling, Ca_w_Ca_signaling, Ca_w_S_signaling,...
                                              GLP1a_mean_GLP1R, GLP1a_cov_GLP1R, conc_mean_GLP1R,...
                                              conc_conv_GLP1R, GLP1R_mean_GLP1R, GLP1R_cov_GLP1R,...
                                              min_cov_GLP1R, GLP1a_w_GLP1R_GLP1R, conc_w_GLP1R_GLP1R,...
                                              Gculture_mean_metabolism, Gculture_cov_metabolism, Ex4_mean_metabolism, ...
                                              Ex4_cov_metabolism, NES_mean_metabolism, NES_cov_metabolism, ...
                                              Pathway_mean_metabolism, Pathway_cov_metabolism, ATP_mean_metabolism, ...
                                              ATP_cov_metabolism, min_cov_metabolism,...
                                              Gculture_w_NES_metabolism, Ex4_w_NES_metabolism, NES_w_Pathway_metabolism,...
                                              Pathway_w_ATP_metabolism  )

    % make DBNs for all input models
    [postprandial_dbn_factory]= make_postprandial_dbn(Gex_mean_postprandial, Y_mean_postprandial, alpha_mean_postprandial,...
                                                      beta_mean_postprandial, gamma_mean_postprandial, k1_mean_postprandial, ...
                                                      k2_mean_postprandial, K_mean_postprandial, dt_mean_postprandial_min, ...
                                                      Gb_mean_postprandial, DGintake_mean_postprandial, Sb_mean_postprandial, ...
                                                      I_mean_postprandial,...
                                                      Gex_cov_postprandial, Y_cov_postprandial, Gb_cov_postprandial, ...
                                                      DGintake_cov_postprandial, Sb_cov_postprandial, I_cov_postprandial,...
                                                      min_cov_postprandial,G_minus_Gb_w_G_postprandial,S_w_I_postprandial);
    [pancreas_dbn_factory]= make_pancreas_dbn(Scell_mean_pancreas, Scell_cov_pancreas, Sislet_mean_pancreas, ...
                                              Sislet_cov_pancreas, Spancreas_mean_pancreas, Spancreas_cov_pancreas, ...
                                              min_cov_pancreas, Scell_w_Sislet_pancreas, Sislet_w_Spancreas_pancreas);
    [exocytosis_dbn_factory]= make_exocytosis_dbn(Gin_mean_exocytosis, k_mean_exocytosis, Npatch_mean_exocytosis,...
                                                  Nisg_mean_exocytosis, Ninsulin_mean_exocytosis, Rpbc_mean_exocytosis,...
                                                  Disg_mean_exocytosis, S_mean_exocytosis, Gin_cov_exocytosis,...
                                                  k_cov_exocytosis, Npatch_cov_exocytosis, Nisg_cov_exocytosis, ...
                                                  Ninsulin_cov_exocytosis, Rpbc_cov_exocytosis,Disg_cov_exocytosis, ...
                                                  S_cov_exocytosis,...
                                                  min_cov_exocytosis,...
                                                  S_w_S_exocytosis, Gin_w_S_exocytosis, S_w_k_exocytosis, ...
                                                  Npatch_w_S_exocytosis,S_w_Nisg_exocytosis, Ninsulin_w_S_exocytosis, ...
                                                  Disg_w_S_exocytosis, Rpbc_w_S_exocytosis);
    [signaling_dbn_factory]= make_signaling_dbn(Gin_mean_signaling, ATP_mean_signaling, GLP1_mean_signaling,...
                                                GLP1R_mean_signaling, cAMP_mean_signaling, Ca_mean_signaling,...
                                                S_mean_signaling, ...
                                                Gin_cov_signaling, ATP_cov_signaling, GLP1_cov_signaling, ...
                                                GLP1R_cov_signaling, cAMP_cov_signaling, Ca_cov_signaling, ...
                                                S_cov_signaling, min_cov_signaling,...
                                                Gin_w_ATP_signaling, ATP_w_ATP_signaling, GLP1_w_GLP1R_signaling,...
                                                ATP_w_cAMP_signaling, GLP1R_w_cAMP_signaling, cAMP_w_cAMP_signaling,...
                                                cAMP_w_Ca_signaling, Ca_w_Ca_signaling, Ca_w_S_signaling);
    [GLP1R_dbn_factory]= make_GLP1R_dbn(GLP1a_mean_GLP1R, GLP1a_cov_GLP1R, conc_mean_GLP1R,...
                                        conc_conv_GLP1R, GLP1R_mean_GLP1R, GLP1R_cov_GLP1R,...
                                        min_cov_GLP1R, GLP1a_w_GLP1R_GLP1R, conc_w_GLP1R_GLP1R);
    [metabolism_dbn_factory]= make_metabolism_dbn(Gculture_mean_metabolism, Gculture_cov_metabolism, Ex4_mean_metabolism, ...
                                                  Ex4_cov_metabolism, NES_mean_metabolism, NES_cov_metabolism, ...
                                                  Pathway_mean_metabolism, Pathway_cov_metabolism, ATP_mean_metabolism, ...
                                                  ATP_cov_metabolism, min_cov_metabolism,...
                                                  Gculture_w_NES_metabolism, Ex4_w_NES_metabolism, NES_w_Pathway_metabolism,...
                                                  Pathway_w_ATP_metabolism);
    
    % make DBNs to generate meta- DBN
    meta_dbn_factory= ...
        merge_dbn_factories(postprandial_dbn_factory, pancreas_dbn_factory, ...
                            exocytosis_dbn_factory, signaling_dbn_factory, GLP1R_dbn_factory, metabolism_dbn_factory);
                     
    % re-define CPDs of connected variables
    weights_Scell0_map_T0= containers.Map(); % parents in slice t
    weights_Scell0_map_T1= containers.Map(); % parents in slice t+1
    weights_Scell0_map_T0('S.exocytosis')= 1/2;
    weights_Scell0_map_T0('S.signaling')= 1/2;
    CPDFactory_Scell0 = ...
        CPDFactory('Gaussian_CPD', 'Scell.ref', 0, {'mean', 0.0, 'cov', S_cov_exocytosis*min_cov_exocytosis}, ...
        weights_Scell0_map_T0, weights_Scell0_map_T1); % Scell.ref = 1/2*S.SPT + 1/2*S.Network
    
    weights_Gin0_map_T0= containers.Map(); 
    weights_Gin0_map_T1= containers.Map(); 
    weights_Gin0_map_T0('Gex.ref')= 0.5;
    CPDFactory_Gin0 = ...
        CPDFactory('Gaussian_CPD', 'Gin.ref', 0, {'mean', 0.0, 'cov', Gin_cov_exocytosis*min_cov_exocytosis}, ...
        weights_Gin0_map_T0, weights_Gin0_map_T1); % Gin.ref = 0.5 * Gex.ref
    
    weights_S0_map_T0= containers.Map();
    weights_S0_map_T1= containers.Map(); 
    weights_S0_map_T0('DGintake.postprandial')= 0.0;
    weights_S0_map_T0('Spancreas.ref')= 2/3;
    weights_S0_map_T0('Y.postprandial')= 0.0;
    CPDFactory_S0 =  ...
        CPDFactory('Gaussian_CPD', 'S.postprandial', 0, {'mean', Sb_mean_postprandial/3, 'cov', Sb_cov_postprandial*min_cov_postprandial}, ...
        weights_S0_map_T0, weights_S0_map_T1); % S.postprandial = 2/3 * Scell.ref
  
    weights_S1_map_T0= containers.Map(); 
    weights_S1_map_T1= containers.Map();
    weights_S1_map_T1('DGintake.postprandial')= K_mean_postprandial/3;
    weights_S1_map_T1('Spancreas.ref')= 2.0/3;
    weights_S1_map_T1('Y.postprandial')= 1.0/3;
    weights_S1_map_T0('S.postprandial')= 0.0;
    CPDFactory_S1=  ...
        CPDFactory('Gaussian_CPD', 'S.postprandial', 1, ...
        {'mean', Sb_mean_postprandial/3, 'cov', Sb_cov_postprandial*min_cov_postprandial}, ...
        weights_S1_map_T0, weights_S1_map_T1); % S(t+1) = 0.0 * S(t) + K_mean_postprandial/3 * DGex(t+1) + 2/3 * Scell.ref(t+1) + 1/3 * Y(t+1)
    
    CPDFactory_GLP1R0=  ...
        CPDFactory('Gaussian_CPD', 'GLP1R.signaling', 0, ...
        {'mean', GLP1R_mean_signaling/2, 'cov', GLP1R_cov_signaling*min_cov_signaling,   'weights', 0.5}); % GLP1R = 0.5 * GLP1R.ref
    
    weights_GLP1R1_T0= containers.Map();
    weights_GLP1R1_T1= containers.Map();
    weights_GLP1R1_T0('GLP1.signaling')= 0.5*GLP1_w_GLP1R_signaling;
    weights_GLP1R1_T0('GLP1R.signaling')= 0.0;
    weights_GLP1R1_T1('GLP1R.ref')= 0.5;
    CPDFactory_GLP1R1=  ...
        CPDFactory('Gaussian_CPD', 'GLP1R.signaling', 1, ...
        {'mean', 0.0, 'cov', GLP1R_cov_signaling*min_cov_signaling}, weights_GLP1R1_T0, weights_GLP1R1_T1); % GLP1R(t+1) = 0.0 * GLP1R(t) + 0.5 * GLP1R.ref(t) + 0.5/GLP1_Network * GLP1(t)
    
    weights_ATP1_T0= containers.Map();
    weights_ATP1_T1= containers.Map(); 
    weights_ATP1_T0('Gin.signaling')= Gin_w_ATP_signaling;
    weights_ATP1_T0('ATP.signaling')= ATP_w_ATP_signaling;
    weights_ATP1_T1('ATP.ref')= 0.0;
    CPDFactory_ATP=  ...
        CPDFactory('Gaussian_CPD', 'ATP.signaling', 1, ...
        {'mean', 0.0, 'cov', ATP_cov_signaling*min_cov_signaling}, weights_ATP1_T0, weights_ATP1_T1);  % ATP(t+1) = ATP_w_ATP_signaling * ATP(t) + Gin_w_ATP_signaling * Gin (t) + 0.5 * ATP.ref
    
    add_CPD_factories(meta_dbn_factory, {CPDFactory_Scell0, CPDFactory_Gin0, CPDFactory_S0,...
                        CPDFactory_S1, CPDFactory_GLP1R0, CPDFactory_GLP1R1, CPDFactory_ATP}, false);

    [meta_dbn, ~, ~, nodes_map] = create_dbn(meta_dbn_factory);
    
end
