% Make a DBN for the exocytosis model with the following variables
%
% Time-dependent variables
%
% Reference variables
% Gex.ref, Gin.ref, Scell.ref
%
% Observed variables
%
% Time-invariant variables
%
% Parameters
%
% To generate a conditional gaussian model
%
% All variables display gaussian distributions.

% To generate a conditional gaussian model
function [dbn_factory]= make_metabolism_dbn(Gculture_mean_metabolism, Gculture_cov_metabolism, Ex4_mean_metabolism, ...
                                            Ex4_cov_metabolism, NES_mean_metabolism, NES_cov_metabolism, ...
                                            Pathway_mean_metabolism, Pathway_cov_metabolism, ATP_mean_metabolism, ...
                                            ATP_cov_metabolism, min_cov_metabolism,...
                                            Gculture_w_NES_metabolism, Ex4_w_NES_metabolism, NES_w_Pathway_metabolism,...
                                            Pathway_w_ATP_metabolism);
    
    node_names=  {'Gculture.metabolism','Gculture.ref','Gculture.obs','Ex4.metabolism','Ex4.ref',...
                  'Ex4.obs','Pathway.metabolism','NES.metabolism','ATP.metabolism','ATP.ref','ATP.obs'}; 
    n= length(node_names);
    
    % Intra - in one time slice
    edges_intra= {'Gculture.ref','Gculture.obs';'Gculture.ref','Gculture.metabolism';'Gculture.metabolism','NES.metabolism';...
                  'Ex4.metabolism','NES.metabolism';'Ex4.metabolism','Ex4.ref';'Ex4.ref','Ex4.obs';...
                  'NES.metabolism','Pathway.metabolism';'Pathway.metabolism','ATP.metabolism';'ATP.metabolism','ATP.ref';...
                  'ATP.ref','ATP.obs'};
    
    % Inter - between time slices
    edges_inter= {}; 
    
    % 'Equivalence classes' specify how the template is initiated and rolled
    % Specify which CPD is associates with each node in either time
    % slice 1 (eclass1) or in slice 2 onwards (eclass2)
    eclass1_map= containers.Map();
    eclass2_map= containers.Map();
    for i=1:numel(node_names)
        node_name= node_names{i};
        cpd_name= [ node_name '.intra' ];
        eclass1_map(node_name) = cpd_name;
        eclass2_map(node_name) = cpd_name; 
    end
    
    % elcass1 (time-slice 0 or all parents are in the same time slice)
    CPDFactories= {};
    CPDFactories{end+1}=  ...
        CPDFactory('Gaussian_CPD', 'Gculture.ref', 0, ...
        {'mean', Gculture_mean_metabolism, 'cov', Gculture_cov_metabolism} ); % Gculture.ref
    
    CPDFactories{end+1}=  ...
        CPDFactory('Gaussian_CPD', 'Gculture.metabolism', 0, ...
        {'mean', 0.0, 'cov', Gculture_cov_metabolism*min_cov_metabolism, 'weights', 1.0} ); % Gculture = Gculture.ref
    
    CPDFactories{end+1}=  ...
        CPDFactory('Gaussian_CPD', 'Gculture.obs', 0, ...
        {'mean', 0.0, 'cov', Gculture_cov_metabolism*min_cov_metabolism, 'weights', 1.0} ); % Gculture.obs = Gculture.ref
    
    CPDFactories{end+1}=  ...
        CPDFactory('Gaussian_CPD', 'Ex4.metabolism', 0, ...
        {'mean', Ex4_mean_metabolism, 'cov', Ex4_cov_metabolism} ); % Ex4
    
    CPDFactories{end+1}=  ...
        CPDFactory('Gaussian_CPD', 'Ex4.ref', 0, ...
        {'mean', 0.0, 'cov', Ex4_cov_metabolism*min_cov_metabolism, 'weights', 1.0} ); % Ex4.ref = Ex4
    
    CPDFactories{end+1}=  ...
        CPDFactory('Gaussian_CPD', 'Ex4.obs', 0, ...
        {'mean', 0.0, 'cov', Ex4_cov_metabolism*min_cov_metabolism, 'weights', 1.0} ); % Ex4.obs = Ex4.ref
    
    CPDFactories{end+1}=  ...
        CPDFactory('Gaussian_CPD', 'NES.metabolism', 0, ...
        {'mean', NES_mean_metabolism, 'cov', NES_cov_metabolism*min_cov_metabolism, 'weights', [Gculture_w_NES_metabolism, Ex4_w_NES_metabolism]} ); % NES = Gculture_w_NES_metabolism * Gculture + Ex4_w_NES_metabolism * Ex4
    
    CPDFactories{end+1}=  ...
        CPDFactory('Gaussian_CPD', 'Pathway.metabolism', 0, ...
        {'mean', Pathway_mean_metabolism, 'cov', Pathway_cov_metabolism*min_cov_metabolism, 'weights', NES_w_Pathway_metabolism} ); % Pathway = NES_w_Pathway_metabolism * NES
    
    CPDFactories{end+1}=  ...
        CPDFactory('Gaussian_CPD', 'ATP.metabolism', 0, ...
        {'mean', ATP_mean_metabolism, 'cov', ATP_cov_metabolism*min_cov_metabolism, 'weights', Pathway_w_ATP_metabolism} ); % ATP =  Pathway_w_ATP_metabolism * Pathwhay
    
    CPDFactories{end+1}=  ...
        CPDFactory('Gaussian_CPD', 'ATP.ref', 0, ...
        {'mean', 0.0, 'cov', ATP_cov_metabolism*min_cov_metabolism, 'weights', 1.0} ); % ATP.ref = ATP
    
    CPDFactories{end+1}=  ...
        CPDFactory('Gaussian_CPD', 'ATP.obs', 0, ...
        {'mean', 0.0, 'cov', ATP_cov_metabolism*min_cov_metabolism, 'weights', 1.0} ); % ATP.obs = ATP.ref
    
    % eclass2 (time-slice t+1 with parents in the previous time slice)

    % Final DBN factory
    dbn_factory= DBNFactory( ...
        node_names, edges_intra, edges_inter, ...
        eclass1_map, eclass2_map, CPDFactories);
  end

