% Sample the meta-modeling DBN containing following five input models:
% 1. The postprandial model
% 2. The exocytosis model
% 3. The signaling model
% 4. The GLP1R model
% 5. The metabolism model

warning('off','MATLAB:singularMatrix');

% ---------------------------------
% Read data as input and evidence
% ---------------------------------
% postprandial model
Json_postprandial = jsondecode(fileread('../data/postprandial_prior_t2d.json'));
DGexp = importdata(Json_postprandial.EvidenceDG);
EvidenceDG = DGexp(:,2);
% pancreas model
Json_pancreas = jsondecode(fileread(['../data/pancreas_prior.json']));
% exocytosis model
Json_exocytosis = jsondecode(fileread(['../data/exocytosis_prior.json']));
% signaling model
Json_signaling = jsondecode(fileread('../data/signaling_prior_normal.json'));
% GLP1R model
Json_GLP1R = jsondecode(fileread('../data/GLP1R_prior.json'));
% metabolism model
Json_metabolism = jsondecode(fileread('../data/metabolism_prior.json'));

[dbn, nodes_map]= make_meta_dbn6(Json_postprandial.DataInput.Gex_mean_postprandial, Json_postprandial.DataInput.Y_mean_postprandial, Json_postprandial.DataInput.alpha_mean_postprandial,...
                                   Json_postprandial.DataInput.beta_mean_postprandial, Json_postprandial.DataInput.gamma_mean_postprandial, Json_postprandial.DataInput.k1_mean_postprandial, ...
                                   Json_postprandial.DataInput.k2_mean_postprandial, Json_postprandial.DataInput.K_mean_postprandial, Json_postprandial.DataInput.dt_mean_postprandial_min, ...
                                   Json_postprandial.DataInput.Gb_mean_postprandial, Json_postprandial.DataInput.DGintake_mean_postprandial, Json_postprandial.DataInput.Sb_mean_postprandial, ...
                                   Json_postprandial.DataInput.I_mean_postprandial,...
                                   Json_postprandial.DataInput.Gex_cov_postprandial, Json_postprandial.DataInput.Y_cov_postprandial, Json_postprandial.DataInput.Gb_cov_postprandial, ...
                                   Json_postprandial.DataInput.DGintake_cov_postprandial, Json_postprandial.DataInput.Sb_cov_postprandial, Json_postprandial.DataInput.I_cov_postprandial,...
                                   Json_postprandial.DataInput.min_cov_postprandial,Json_postprandial.DataInput.G_minus_Gb_w_G_postprandial,Json_postprandial.DataInput.S_w_I_postprandial,...
                                   Json_pancreas.DataInput.Scell_mean_pancreas, Json_pancreas.DataInput.Scell_cov_pancreas, Json_pancreas.DataInput.Sislet_mean_pancreas, ...
                                   Json_pancreas.DataInput.Sislet_cov_pancreas, Json_pancreas.DataInput.Spancreas_mean_pancreas, Json_pancreas.DataInput.Spancreas_cov_pancreas, ...
                                   Json_pancreas.DataInput.min_cov_pancreas, Json_pancreas.DataInput.Scell_w_Sislet_pancreas, Json_pancreas.DataInput.Sislet_w_Spancreas_pancreas,...
                                   Json_exocytosis.DataInput.Gin_mean_exocytosis, Json_exocytosis.DataInput.k_mean_exocytosis, Json_exocytosis.DataInput.Npatch_mean_exocytosis,...
                                   Json_exocytosis.DataInput.Nisg_mean_exocytosis, Json_exocytosis.DataInput.Ninsulin_mean_exocytosis, Json_exocytosis.DataInput.Rpbc_mean_exocytosis,...
                                   Json_exocytosis.DataInput.Disg_mean_exocytosis, Json_exocytosis.DataInput.S_mean_exocytosis, Json_exocytosis.DataInput.Gin_cov_exocytosis,...
                                   Json_exocytosis.DataInput.k_cov_exocytosis, Json_exocytosis.DataInput.Npatch_cov_exocytosis, Json_exocytosis.DataInput.Nisg_cov_exocytosis, ...
                                   Json_exocytosis.DataInput.Ninsulin_cov_exocytosis, Json_exocytosis.DataInput.Rpbc_cov_exocytosis,Json_exocytosis.DataInput.Disg_cov_exocytosis, ...
                                   Json_exocytosis.DataInput.S_cov_exocytosis,...
                                   Json_exocytosis.DataInput.min_cov_exocytosis,...
                                   Json_exocytosis.DataInput.S_w_S_exocytosis, Json_exocytosis.DataInput.Gin_w_S_exocytosis, Json_exocytosis.DataInput.S_w_k_exocytosis, ...
                                   Json_exocytosis.DataInput.Npatch_w_S_exocytosis,Json_exocytosis.DataInput.S_w_Nisg_exocytosis, Json_exocytosis.DataInput.Ninsulin_w_S_exocytosis, ...
                                   Json_exocytosis.DataInput.Disg_w_S_exocytosis,Json_exocytosis.DataInput.Rpbc_w_S_exocytosis,...
                                   Json_signaling.DataInput.Gin_mean_signaling, Json_signaling.DataInput.ATP_mean_signaling, Json_signaling.DataInput.GLP1_mean_signaling,...
                                   Json_signaling.DataInput.GLP1R_mean_signaling, Json_signaling.DataInput.cAMP_mean_signaling, Json_signaling.DataInput.Ca_mean_signaling,...
                                   Json_signaling.DataInput.S_mean_signaling, ...
                                   Json_signaling.DataInput.Gin_cov_signaling, Json_signaling.DataInput.ATP_cov_signaling, Json_signaling.DataInput.GLP1_cov_signaling, ...
                                   Json_signaling.DataInput.GLP1R_cov_signaling, Json_signaling.DataInput.cAMP_cov_signaling, Json_signaling.DataInput.Ca_cov_signaling, ...
                                   Json_signaling.DataInput.S_cov_signaling, Json_signaling.DataInput.min_cov_signaling,...
                                   Json_signaling.DataInput.Gin_w_ATP_signaling, Json_signaling.DataInput.ATP_w_ATP_signaling, Json_signaling.DataInput.GLP1_w_GLP1R_signaling,...
                                   Json_signaling.DataInput.ATP_w_cAMP_signaling, Json_signaling.DataInput.GLP1R_w_cAMP_signaling, Json_signaling.DataInput.cAMP_w_cAMP_signaling,...
                                   Json_signaling.DataInput.cAMP_w_Ca_signaling, Json_signaling.DataInput.Ca_w_Ca_signaling, Json_signaling.DataInput.Ca_w_S_signaling,...
                                   Json_GLP1R.DataInput.GLP1a_mean_GLP1R, Json_GLP1R.DataInput.GLP1a_cov_GLP1R, Json_GLP1R.DataInput.conc_mean_GLP1R,...
                                   Json_GLP1R.DataInput.conc_conv_GLP1R, Json_GLP1R.DataInput.GLP1R_mean_GLP1R, Json_GLP1R.DataInput.GLP1R_cov_GLP1R,...
                                   Json_GLP1R.DataInput.min_cov_GLP1R, Json_GLP1R.DataInput.GLP1a_w_GLP1R_GLP1R, Json_GLP1R.DataInput.conc_w_GLP1R_GLP1R,...
                                   Json_metabolism.DataInput.Gculture_mean_metabolism, Json_metabolism.DataInput.Gculture_cov_metabolism, Json_metabolism.DataInput.Ex4_mean_metabolism, ...
                                   Json_metabolism.DataInput.Ex4_cov_metabolism, Json_metabolism.DataInput.NES_mean_metabolism, Json_metabolism.DataInput.NES_cov_metabolism, ...
                                   Json_metabolism.DataInput.Pathway_mean_metabolism, Json_metabolism.DataInput.Pathway_cov_metabolism, Json_metabolism.DataInput.ATP_mean_metabolism,...
                                   Json_metabolism.DataInput.ATP_cov_metabolism, Json_metabolism.DataInput.min_cov_metabolism,...
                                   Json_metabolism.DataInput.Gculture_w_NES_metabolism, Json_metabolism.DataInput.Ex4_w_NES_metabolism, Json_metabolism.DataInput.NES_w_Pathway_metabolism,...
                                   Json_metabolism.DataInput.Pathway_w_ATP_metabolism);


npers= dbn.nnodes_per_slice;
dbn_engine = jtree_dbn_inf_engine(dbn);

% Time slices to sample
for GLP1_evidence = [0 Json_signaling.EvidenceInput.GLP1_1 ...
                     Json_signaling.EvidenceInput.GLP1_2 ...
                     Json_signaling.EvidenceInput.GLP1_3 Json_signaling.EvidenceInput.GLP1_4]
    evidence=cell(npers,Json_postprandial.DataInput.T);
    for measure = 1:Json_postprandial.DataInput.T
        evidence{nodes_map('DGintake.obs'),measure} = EvidenceDG(measure);
        evidence{nodes_map('GLP1.obs'),measure} = GLP1_evidence; 
        %evidence{nodes_map('GLP1a.obs'),measure} = 0; 
        %evidence{nodes_map('conc.obs'),measure} = 0; 
        %evidence{nodes_map('Gculture.obs'),measure} = 0; 
        %evidence{nodes_map('Ex4.obs'),measure} = 0;
    end

    [engine, ll] = enter_evidence(dbn_engine, evidence);
    %disp(ll);

    % Create a table with the data and variable names
    T = table();

    for node_name = ["Gex.ref" "Gin.ref" "Scell.ref" "GLP1R.ref" ...
             "Gex.postprandial" "S.postprandial" "Gb.postprandial" ...
             "I.postprandial" "Gin.exocytosis" "k.exocytosis" ...
             "Npatch.exocytosis" "Nisg.exocytosis" "Gin.ref" "Ninsulin.exocytosis" ...
             "S.exocytosis" "Gin.signaling" "cAMP.signaling" ...
             "Ca.signaling" "S.signaling"]
        node_values = {};
        node_values(end+1,:) = {node_name,node_name,node_name}
        for slice = 1:Json_postprandial.DataInput.T 
            marg = marginal_nodes(engine,nodes_map(node_name),slice);
            node_values(end+1,:) = {marg.mu, marg.Sigma, sqrt(marg.Sigma)};
        end
        T = [T node_values];
    end 

    % Write data to text file
    fname = sprintf('../results/metamodel_t2d_GLP1_%d.csv', GLP1_evidence);
    writetable(T, fname);
end